### PR TITLE
Add instructions on how to get to fastboot

### PR DESCRIPTION
**Pull request by TheLastProject**

### CODE REVIEW

**Comment by jrtberlin** [comment]
Hi, since `ADB` mode is not the default: Is there any reason you decided to document the `ADB` method instead of using `SSH`? 
`ssh root@192.168.2.15 'reboot -f bootloader'`

**Comment by TheLastProject** [comment]
Well, ADB mode worked for me. I didn't try SSH mode. I can add the Developer Mode instructions too if you want.

**Comment by jrtberlin** [comment]
> Well, ADB mode worked for me. I didn't try SSH mode. I can add the Developer Mode instructions too if you want.

Would be great if you could add this. Explaining both is probably good if one of them doesn't work for a user.
Thank you for improving the docs!

**Comment by jrtberlin** [comment]
Thank you for improving our documentation!

**Pull request merged**
