### PR TITLE
Shorten headlines to make the menubar better legible and not clip

### PR DESCRIPTION
**Pull request by eLtMosen**
image

This solves the clipping

image

But question is if the text is possibly too short now.

### CODE REVIEW

**Review by beroset — APPROVED** [review]
Nice!  I think this is an improvement and makes it easier to scan the questions in the sidebar.

**Comment by eLtMosen** [comment]
Visual after furtheer optimization

image

**Comment by FlorentRevest** [comment]
Thanks, I like this sort of simplification. Generally speaking our website should be "straight to the point". That's a good step already

**Comment by FlorentRevest** [comment]
(although this clipping is a bug and should be fixed separately)

**Pull request merged**
