### PR TITLE
Fix and improve the build instructions

### PR DESCRIPTION
**Pull request by T-vK**

### CODE REVIEW

**Comment by T-vK** [comment]
Well, I have personally tested the build on Debian Sid. I'm not sure if we can say this has been tested on Ubuntu until we have done so on a fresh/clean system using the updated instructions. But I'd happily run another build in Ubuntu if you tell me which Ubuntu version I should use.

**Comment by FlorentRevest** [comment]
I'd prefer if we'd recommend an Ubuntu LTS, so 18.04.

**Comment by T-vK** [comment]
Alright, I'll let the build run and see if if it works and update this PR then.

**Comment by T-vK** [comment]
The `python2` package is called `python2.7` on Ubuntu, so I adjusted that, but I still get this error then:

```
/home/asteroid/asteroid/src/oe-core/scripts/oe-buildenv-internal: line 43: python2: command not found
OpenEmbedded requires 'python' to be python v2 (>= 2.7.3), not python v3.
Please upgrade your python v2.
```

If I don't install `python3`, I still get that error and in addition to that I also get:

```
/home/asteroid/asteroid/src/oe-core/scripts/oe-buildenv-internal: line 53: python3: command not found
BitBake requires Python 3.4.0 or later as 'python3'
```

**Comment by FlorentRevest** [comment]
Err... What about 19.04 then?

**Comment by T-vK** [comment]
Same error.

**Comment by T-vK** [comment]
Turns out on Ubuntu 19 you don't just have `python2.7`, but also `python2`, which is not available on Ubuntu 18. And now the build works just fine. :)

**Comment by T-vK** [comment]
Anything else you'd like me to change in the PR?

**Comment by FlorentRevest** [comment]
Thank you @T-vK !
No there wasn't anything else you should have changed, I was just busy the past couple of days.
For your download problems, please report this to the OpenEmbedded project which maintains the build system that AsteroidOS uses.

**Comment by T-vK** [comment]
Just to make sure, I'm talking about errors like this:

```
Now at patch 0001-Advertise-hostname-in-BLE-ad-payload-to-have-a-recog.patch
WARNING: libmlocale-+gitAUTOINC+8ba84e50a3-r1 do_fetch: Failed to fetch URL git://git.merproject.org/mer-core/libmlocale.git;protocol=https, attempting MIRRORS if available
ERROR: libmlocale-+gitAUTOINC+8ba84e50a3-r1 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/home/asteroid/asteroid/src/oe-core/scripts:/home/asteroid/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/libmlocale/+gitAUTOINC+8ba84e50a3-r1/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi:/home/asteroid/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/libmlocale/+gitAUTOINC+8ba84e50a3-r1/recipe-sysroot/usr/bin/crossscripts:/home/asteroid/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/libmlocale/+gitAUTOINC+8ba84e50a3-r1/recipe-sysroot-native/usr/sbin:/home/asteroid/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/libmlocale/+gitAUTOINC+8ba84e50a3-r1/recipe-sysroot-native/usr/bin:/home/asteroid/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/libmlocale/+gitAUTOINC+8ba84e50a3-r1/recipe-sysroot-native/sbin:/home/asteroid/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/libmlocale/+gitAUTOINC+8ba84e50a3-r1/recipe-sysroot-native/bin:/home/asteroid/asteroid/src/oe-core/bitbake/bin:/home/asteroid/asteroid/build/tmp-glibc/hosttools"; export HOME="/home/asteroid"; LANG=C git -c core.fsyncobjectfiles=0 clone --bare --mirror https://git.merproject.org/mer-core/libmlocale.git /home/asteroid/asteroid/build/downloads/git2/git.merproject.org.mer-core.libmlocale.git --progress failed with exit code 128, output:
Cloning into bare repository '/home/asteroid/asteroid/build/downloads/git2/git.merproject.org.mer-core.libmlocale.git'...
remote: Enumerating objects: 122, done.        
remote: Counting objects: 100% (122/122), done.        
remote: Compressing objects: 100% (121/121), done.        
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

ERROR: libmlocale-+gitAUTOINC+8ba84e50a3-r1 do_fetch: Fetcher failure for URL: 'git://git.merproject.org/mer-core/libmlocale.git;protocol=https'. Unable to fetch URL from any source.
ERROR: libmlocale-+gitAUTOINC+8ba84e50a3-r1 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/asteroid/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/libmlocale/+gitAUTOINC+8ba84e50a3-r1/temp/log.do_fetch.27237
ERROR: Task (/home/asteroid/asteroid/src/meta-asteroid/recipes-nemomobile/libmlocale/libmlocale_git.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1628 tasks of which 5 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/asteroid/asteroid/src/meta-asteroid/recipes-nemomobile/libmlocale/libmlocale_git.bb:do_fetch
Summary: There were 3 WARNING messages shown.
Summary: There were 3 ERROR messages shown, returning a non-zero exit code.
```

Are you sure this is something that has to be fixed by `OpenEmbedded`?

**Comment by FlorentRevest** [comment]
There seems to be various possible explanations to the error you just pasted, one of which could be that the version of git you use should be recompiled with some openssl parameters or that the nemomobile server should fix their TLS installation somehow https://github.com/git/git-scm.com/issues/717 
Some people just purge and reinstall git and it ends up working https://github.com/bluegeek/blog/issues/14
Some people change their git configuration http://sarathblogs.blogspot.com/2017/02/solved-fix-for-git-clone-failure-due-to.html
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=870052

Anyway, this does not seem to fit into the asteroid project. If you want to ask for bitbake to try to clone repositories multiple times, then you could ask the OpenEmbedded guys but they will probably tell you that you should fix what's wrong with your git installation first. (or what's wrong with the nemomobile server, if anything is wrong there)

**Comment by T-vK** [comment]
Alright, thank you. :)

**Pull request merged**
