### PR TITLE
Removed google-analytics.com integration.

### PR DESCRIPTION
**Pull request by kratz00**
First pull request to improve user privacy (see issue #19).

### CODE REVIEW

**Comment by FlorentRevest** [comment]
I'm afraid we may have had a misunderstanding @kratz00. With "replacing the services provided by the CDNs" I did not mean "suppressing the services provided by the CDNs" https://github.com/AsteroidOS/asteroidos.org/issues/19#issuecomment-399567464
We rely on analytics's dashboard to better understand what brings people to AsteroidOS and how we can help them better. If you think this service would be better served by a self-hosted system or a different company, feel free to propose an alternative with equivalent services but just suppressing a functionality is not satisfying.
As a simple reminder (I'm sure you already know about this), I'd also add that you can install addons to your browser to remove calls to google-analytics from the client side. If this is something you truly care about, you'd probably want to have this installed.

**Comment by FlorentRevest** [comment]
Hi @kratz00. Sure that sounds like something we could do. I'll check this up with the server's admin and let you know if/when it happens.

**Comment by kratz00** [comment]
Great :+1:

**Comment by kratz00** [comment]
Cool, thanks for replacing google-analytics.com with your own/self-hosted solution. :+1:

**Pull request closed without merging**
