### PR TITLE
[Install pages] Adapt support table width to full container width

### PR DESCRIPTION
**Pull request by eLtMosen**
The support table was fixed width and looked off after adding the model number table.
This PR
- Makes the support table behave visually like the model number table
- Is tailored to our current max 15 items worst case table for beluga and catfish

This method prevents horizontal scrolling down to a minimum screen width of 520px.

Before

https://user-images.githubusercontent.com/15074193/222451491-14bfea44-ab12-42e9-bd93-39e709b86b4b.mp4

After, for current worst case catfish

https://user-images.githubusercontent.com/15074193/222452283-a7b09ed6-3820-4620-bf7d-16500b5e9fad.mp4

### CODE REVIEW

**Comment by FlorentRevest** [comment]
Thanks for all the efforts and recording the videos and everything :D

**Comment by eLtMosen** [comment]
Downsides needing fix:

- Due to tailoring to catfish/beluga, watches with fewer features have their titles shrunk unnecessarily small
- This sort of hardcoded and would need adaption as soon as a new feature is added.

**Comment by eLtMosen** [comment]
New design to remove the downsides of previuos approach.
- Feature name moved into to feature status div
- Colors adapted to work as background color for black text
- Feature boxes keep the size and break into rows when the screen width is reduced

grafik

grafik

**Comment by FlorentRevest** [comment]
Looks very cool, great work! Thank you @eLtMosen

**Review by FlorentRevest — APPROVED** [review]

**Comment by eLtMosen** [comment]
> Looks very cool, great work! Thank you @eLtMosen

@dodoradio greatly helped to polish it!

**Comment by FlorentRevest** [comment]
Thanks dodo too!

Just a note, it seems that you introduced a stray "<h1>Preparation</h1>" title before "" in the MTK6580 watches page https://asteroidos.org/install/harmony/

**Comment by FlorentRevest** [comment]
https://asteroidos.org/install/beluga/ also has a stray "Hardware Support" :)

**Pull request merged**
