### PR TITLE
install: Change watch ratings and reorder.

### PR DESCRIPTION
**Pull request by MagneFire**
As discussed in https://github.com/AsteroidOS/asteroidos.org/issues/80

Also took the liberty to allow for markdown in content files :smile:

The watch stars is pretty much a copy of the current issue. Let me know if you agree with the current star rating. I based it on the current support matrix and the general support right now of the watches.

### CODE REVIEW

**Comment by FlorentRevest** [comment]
I'd give dory 4 stars. It used to be our best supported watch (before bass). The main issue is a race condition in the bluetooth initialization. Otherwise it works fairly well. The rest LGTM.

**Review by FlorentRevest — APPROVED** [review]

**Comment by MagneFire** [comment]
The reason I gave `dory` 3 stars is because tilt-to-wake isn't working on it. But if it is otherwise good than increasing its stars to 4 is good too.

**Comment by FlorentRevest** [comment]
Makes sense :) I'm fine with 3 stars for dory then

**Comment by MagneFire** [comment]
ok, reverted my last commit back to what it was :smile:

**Pull request merged**
